name: Triggered Workflow

on:
  repository_dispatch:
    types: [servicenow-change-approved]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo trigger
        run: echo "Triggered by ServiceNow Change Approval"
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Notify ServiceNow
        run: |
              curl -X POST "https:dev252430.service-now.com/api/xyourscope/github_response/workflow-response" \
              -H "Content-Type: application/json" \
              -u "${{ secrets.SNUSERNAME }}:${{ secrets.SNPASSWORD }}" \
              -d '{
              "workflow_id": "${{ github.workflow }}",
              "status": "completed",
              "output": "All steps passed"
                  }'
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7  # Or your preferred version

    - name: Deploy with Terraform
      run: |
        cd terraform
        terraform init
        terraform plan
        terraform apply -auto-approve
